#!/usr/bin/env bash 
# install nginx on my server
apt-get update
apt-get -y install nginx

service nginx start 

sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "hello world!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart