#!/usr/bin/env bash 
# install nginx on my server
apt-get update
apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "hello world!" > /var/www/html/index.html

service nginx start 