#!/usr/bin/env bash 
#confrigre redirection 

sudo apt update 
sudo apt install nginx -y 
sudo service nginx start

sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable 
echo "hello world!" > /var/www/html/index.nginx-debian.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=tTGurm3LxZs&list=PLqjy2IHnuqJvxlg3qaOuDPok1G-rp-HEM permanent;' /etc/nginx/sites-available/default

echo "there is no page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart